apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: golist
spec:
  source:
    path: argocd/applications
    repoURL: 'https://github.com/christianh814/golist'
    targetRevision: akuity
  destination:
    namespace: argocd
    name: in-cluster
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 5s
        maxDuration: 3m0s
        factor: 2
    syncOptions:
      - CreateNamespace=true
