---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: golist-db-pvc
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
