apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  name: golist-frontend
  namespace: argocd
spec:
  project: default
  source:
    path: apps/golist-frontend
    repoURL: 'https://github.com/christianh814/golist'
    targetRevision: main
  destination:
    namespace: golist
    name: my-kind-cluster
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 5s
        maxDuration: 3m0s
        factor: 2
    syncOptions:
      - CreateNamespace=true
